version: '3.8'

networks:
  redisn:
    driver: bridge

services:
  redis1:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data_1:/bitnami/redis/data
    networks: 
      - redisn

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redis-insight
    volumes: 
      - redis-insight:/data
    ports:
      - "5540:5540" 
    networks: 
      - redisn
    depends_on:
      - redis1


volumes:
  redis_data_1:
    driver: local
  redis-insight: